# Use Airbnb rules to check code
extends:
  - airbnb-typescript

parserOptions:
  project: './tsconfig.json'

plugins:
  - chai-friendly

rules:
  # Allow chai test assertions to occur without eslint throwing errors
  "@typescript-eslint/no-unused-expressions": off
  chai-friendly/no-unused-expressions: error
