# Use Airbnb rules to check code
extends:
  - airbnb-typescript

parserOptions:
  project: './tsconfig.json'

plugins:
  - chai-friendly

settings:
  # Modules that should be a devDependency and will be used in the application
  import/core-modules:
    - electron

rules:
  # Turn off linting about having wrong line ending, handled in .gitattributes
  linebreak-style: off

  # Allow chai test assertions to occur without eslint throwing errors
  "@typescript-eslint/no-unused-expressions": off
  chai-friendly/no-unused-expressions: error
