# Travis CI testing configuration

language: node_js

# Use latest version of Node.js
node_js:
  - lts/*

# Scripts to run to test application
script:
  - npm test

# Scripts to run after build success/failure
after_success:
  - npm run coverage
  - chmod +x script/webhook.sh
  - ./script/webhook.sh success
after_failure:
  - chmod +x script/webhook.sh
  - ./script/webhook.sh failure
