# Travis CI testing configuration

language: node_js

# Install fossa-cli
before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

# Use latest version of Node.js
node_js:
  - lts/*

# Cache node_modules after testing
cache: npm

# Scripts to run to test application
script:
  # Run each test manually instead of npm test so that it runs sequentially (and not in parallel)
  - npm run test:lint
  - npm run test:types
  - npm run test:unit

  - fossa init
  - fossa analyze
  - fossa test
